---
title: "R Notebook"
output: rmarkdown::github_document
---

```{r}
library(readr)
customers_data_2 <- read_csv("C:/Users/Admin/Downloads/Wholesale customers data.csv")
customers_data <- customers_data_2
head(customers_data)
```

```{r}
tail(customers_data)
```

```{r}
# Checking all column names

names(customers_data)
```


```{r}
# Checking the data types of each column

str(customers_data)
```

```{r}
summary(customers_data)
```
```{r}
# Checking the number of unique values in each column

lengths(lapply(customers_data, unique))
```


```{r}
# Checking for null values

is.null(customers_data)
```

```{r}
# Checking for Duplicate records

anyDuplicated(customers_data)
```

```{r}
# install.packages("magrittr") # package installations are only needed the first time you use it
# install.packages("dplyr")    # alternative installation of the %>%
library(magrittr) # needs to be run every time you start R and want to use %>%
library(dplyr)    # alternatively, this also loads %>%
```

```{r}
names(customers_data[, 1])
```

```{r}
customers_data[, is.numeric(customers_data)]
```


```{r}
num.cols <- unlist(lapply(customers_data, is.numeric))         
num.cols

# -num.cols- being a condition
data.num <- customers_data[ , num.cols]                        
data.num 
```


```{r}
# Creating a variable with only numeric attributes

data.num <- customers_data[ , unlist(lapply(customers_data, is.numeric))]


# Boxplot loop
for (i in 1:ncol(data.num)) {
  boxplot(data.num[, i], main=names(data.num[, i]))
}

```



```{r}
customers_data$Channel <- as.character(customers_data$Channel)

customers_data$Channel[customers_data$Channel == "1"] <- "restaurant"
customers_data$Channel[customers_data$Channel == "2"] <- "retail"
```

```{r}
customers_data$Region <- as.character(customers_data$Region)

customers_data$Region[customers_data$Region == "1"] <- "Lisbon"
customers_data$Region[customers_data$Region == "2"] <- "Porto"
customers_data$Region[customers_data$Region == "3"] <- "Other region"
```



```{r}
# Calculating the mean for all numeric columns

colMeans(data.num)
```

```{r}
for (i in 1:ncol(data.num)) {
  data.num[, i] <- as.numeric(unlist(data.num[, i]))
}
```

```{r}
median(as.numeric(unlist(data.num[, 1])))
```



```{r}
for (i in 1:ncol(data.num)) {
  print(names(as.vector(data.num[, i])))
  print(median(as.numeric(unlist(data.num[, i]))))
  print("**************")
}
```


```{r}
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}
```

```{r}
for (i in 1:ncol(customers_data)) {
  print(names(customers_data[, i]))
  print(getmode(customers_data[, i]))
}
```

```{r}
# install.packages("matrixStats")
library(matrixStats)
```
```{r}
for (i in 1:ncol(data.num)) {
  print(names(as.vector(data.num[, i])))
  print(min(as.numeric(unlist(data.num[, i]))))
  print("**************")
}
```


```{r}
for (i in 1:ncol(data.num)) {
  print(names(as.vector(data.num[, i])))
  print(max(as.numeric(unlist(data.num[, i]))))
  print("**************")
}
```


```{r}
lapply(data.num,FUN=quantile)
```

```{r}

# Checking the range for all numeric columns

lapply(data.num,FUN=range)
```

```{r}
for (i in 1:ncol(data.num)) {
  print(names(as.vector(data.num[, i])))
  print(var(as.numeric(unlist(data.num[, i]))))
  print("**************")
}
```

```{r}
for (i in 1:ncol(data.num)) {
  print(names(as.vector(data.num[, i])))
  print(sd(as.numeric(unlist(data.num[, i]))))
  print("**************")
}
```

```{r}
for (i in 1:ncol(data.num)) {
  hist(as.numeric(unlist(data.num[, i])))
}
```






